
# a dict that maps pyStxm names to Pixelator names
app_to_dcs_devname_map = {}
app_to_dcs_devname_map['DNM_MOENCH_NUM_FRAMES'] = 'MoenchNumFrames'
app_to_dcs_devname_map['DNM_SAMPLE_FINE_X'] = 'FineX'
app_to_dcs_devname_map['DNM_SAMPLE_FINE_Y'] = 'FineY'
app_to_dcs_devname_map['DNM_OSA_X'] = 'OSAX'
app_to_dcs_devname_map['DNM_OSA_Y'] = 'OSAY'
app_to_dcs_devname_map['DNM_ZONEPLATE_Z'] = 'Zoneplate'
app_to_dcs_devname_map['DNM_COARSE_X'] = 'CoarseX'
app_to_dcs_devname_map['DNM_COARSE_Y'] = 'CoarseY'
app_to_dcs_devname_map['DNM_COARSE_Z'] = ''
app_to_dcs_devname_map['DNM_DETECTOR_X'] = 'DetectorX'
app_to_dcs_devname_map['DNM_DETECTOR_Y'] = 'DetectorY'
app_to_dcs_devname_map['DNM_DETECTOR_Z'] = 'DetectorZ'
app_to_dcs_devname_map['DNM_SAMPLE_X'] = 'SampleX'
app_to_dcs_devname_map['DNM_SAMPLE_Y'] = 'SampleY'
app_to_dcs_devname_map['DNM_ENERGY'] = 'Energy'
app_to_dcs_devname_map['DNM_SLIT_X'] = ''
app_to_dcs_devname_map['DNM_SLIT_Y'] = ''
app_to_dcs_devname_map['DNM_M3_PITCH'] = ''
app_to_dcs_devname_map['DNM_EPU_GAP'] = ''
app_to_dcs_devname_map['DNM_EPU_OFFSET'] = 'ID1Off'
app_to_dcs_devname_map['DNM_ID2_OFFSET'] = 'ID2Off'
app_to_dcs_devname_map['DNM_EPU_HARMONIC'] = ''
app_to_dcs_devname_map['DNM_EPU_POLARIZATION'] = 'Polarization'
app_to_dcs_devname_map['DNM_EPU_ANGLE'] = ''
app_to_dcs_devname_map['DNM_SHUTTER'] = 'BeamShutter'
app_to_dcs_devname_map['DNM_SHUTTERTASKRUN'] = ''
app_to_dcs_devname_map['DNM_SIS3820'] = ''
app_to_dcs_devname_map['DNM_PMT'] = 'Counter0'
app_to_dcs_devname_map['DNM_TUCSEN_AD'] = ''
app_to_dcs_devname_map['DNM_FINE_ACCEL_DIST_PRCNT'] = ''
app_to_dcs_devname_map['DNM_FINE_DECCEL_DIST_PRCNT'] = ''
app_to_dcs_devname_map['DNM_CRS_ACCEL_DIST_PRCNT'] = ''
app_to_dcs_devname_map['DNM_CRS_DECCEL_DIST_PRCNT'] = ''
app_to_dcs_devname_map['DNM_CALCD_ZPZ'] = ''
app_to_dcs_devname_map['DNM_RESET_INTERFERS'] = ''
app_to_dcs_devname_map['DNM_SFX_AUTOZERO'] = ''
app_to_dcs_devname_map['DNM_SFY_AUTOZERO'] = ''
app_to_dcs_devname_map['DNM_ZPZ_ADJUST'] = ''
app_to_dcs_devname_map['DNM_ZONEPLATE_SCAN_MODE'] = ''
app_to_dcs_devname_map['DNM_ZONEPLATE_SCAN_MODE_RBV'] = ''
app_to_dcs_devname_map['DNM_DELTA_A0'] = ''
app_to_dcs_devname_map['DNM_IDEAL_A0'] = ''
app_to_dcs_devname_map['DNM_CALCD_ZPZ'] = ''
app_to_dcs_devname_map['DNM_ZPZ_ADJUST'] = ''
app_to_dcs_devname_map['DNM_FOCAL_LENGTH'] = ''
app_to_dcs_devname_map['DNM_A0'] = 'PIXELATOR_A0'
app_to_dcs_devname_map['DNM_A0MAX'] = 'PIXELATOR_A0MAX'
app_to_dcs_devname_map['DNM_ZPZ_POS'] = ''
app_to_dcs_devname_map['DNM_ENERGY_ENABLE'] = ''
app_to_dcs_devname_map['DNM_ENERGY_RBV'] = ''
app_to_dcs_devname_map['DNM_ZPZ_RBV'] = ''
app_to_dcs_devname_map['DNM_ZP_DEF_A'] = ''
app_to_dcs_devname_map['DNM_ZP_DEF'] = ''
app_to_dcs_devname_map['DNM_OSA_DEF'] = ''
app_to_dcs_devname_map['DNM_SYSTEM_MODE_FBK'] = ''
app_to_dcs_devname_map['DNM_SRSTATUS_SHUTTERS'] = ''
#app_to_dcs_devname_map['DNM_MONO_EV_FBK'] = 'Energy'
app_to_dcs_devname_map['DNM_BEAM_DEFOCUS'] = ''
app_to_dcs_devname_map['DNM_AX1_INTERFER_VOLTS'] = ''
app_to_dcs_devname_map['DNM_SFX_PIEZO_VOLTS'] = ''
app_to_dcs_devname_map['DNM_SFY_PIEZO_VOLTS'] = ''
app_to_dcs_devname_map['DNM_AX2_INTERFER_VOLTS'] = ''
app_to_dcs_devname_map['DNM_RING_CURRENT'] = 'PIXELATOR_RING_CURRENT'
app_to_dcs_devname_map['DNM_BASELINE_RING_CURRENT'] = ''
app_to_dcs_devname_map['DNM_DFLT_PMT_DWELL'] = ''
app_to_dcs_devname_map['DNM_TICKER'] = ''
app_to_dcs_devname_map['DNM_ZONEPLATE_INOUT'] = 'PIXELATOR_ZONEPLATE_INOUT'
app_to_dcs_devname_map['DNM_OSA_INOUT'] = 'PIXELATOR_OSA_INOUT'
app_to_dcs_devname_map['DNM_SAMPLE_OUT'] = 'PIXELATOR_SAMPLE_OUT'
app_to_dcs_devname_map['DNM_RESET_INTERFERS'] = 'PIXELATOR_RESET_INTERFERS'
app_to_dcs_devname_map['DNM_ALL_MOTORS_OFF'] = 'PIXELATOR_ALL_MOTORS_OFF'
app_to_dcs_devname_map['DNM_GATING'] = 'PIXELATOR_GATING'
app_to_dcs_devname_map['DNM_FOCUS_MODE'] = 'PIXELATOR_FOCUS_MODE'


# dcs_to_app_devname_map = {}
# dcs_to_app_devname_map['MoenchNumFrames'] = 'DNM_MOENCH_NUM_FRAMES'
# dcs_to_app_devname_map['FineX'] = 'DNM_SAMPLE_FINE_X'
# dcs_to_app_devname_map['FineY'] = 'DNM_SAMPLE_FINE_Y'
# dcs_to_app_devname_map['OSAX'] = 'DNM_OSA_X'
# dcs_to_app_devname_map['OSAY'] = 'DNM_OSA_Y'
# dcs_to_app_devname_map['Zoneplate'] = 'DNM_ZONEPLATE_Z'
# dcs_to_app_devname_map['CoarseX'] = 'DNM_COARSE_X'
# dcs_to_app_devname_map['CoarseY'] = 'DNM_COARSE_Y'
# dcs_to_app_devname_map['DetectorX'] = 'DNM_DETECTOR_X'
# dcs_to_app_devname_map['DetectorY'] = 'DNM_DETECTOR_Y'
# dcs_to_app_devname_map['DetectorZ'] = 'DNM_DETECTOR_Z'
# dcs_to_app_devname_map['SampleX'] = 'DNM_SAMPLE_X'
# dcs_to_app_devname_map['SampleY'] = 'DNM_SAMPLE_Y'
# dcs_to_app_devname_map['Energy'] = 'DNM_ENERGY'
# dcs_to_app_devname_map['ID1Off'] = 'DNM_EPU_OFFSET'
# dcs_to_app_devname_map['ID2Off'] = 'DNM_ID2_OFFSET'
# dcs_to_app_devname_map['Polarization'] = 'DNM_EPU_POLARIZATION'
# dcs_to_app_devname_map['BeamShutter'] = 'DNM_SHUTTER'
# dcs_to_app_devname_map['Counter0'] = 'DNM_PMT'


# for app_devname in app_to_dcs_devname_map.keys():
#     print(f"dcs_to_app_devname_map['{app_to_dcs_devname_map[app_devname]}'] = '{app_devname}'")
#
#
#
# no use this to create a reversable search map
#print("dcs_to_app_devname_map = {}")
dcs_to_app_devname_map = {}
for app_devname in app_to_dcs_devname_map.keys():
    #print(f"dcs_to_app_devname_map['{app_to_dcs_devname_map[app_devname]}'] = '{app_devname}'")
    if len(app_to_dcs_devname_map[app_devname]) > 0:
        dcs_to_app_devname_map[app_to_dcs_devname_map[app_devname]] = app_devname
