motor_limits = [
    {'dcs_devname':'PIXELATOR_SAMPLE_FINE_X', 'low_limit': -7500, 'high_limit': 7500},
    {'dcs_devname':'PIXELATOR_SAMPLE_FINE_Y', 'low_limit': -7500, 'high_limit': 7500},
    {'dcs_devname':'PIXELATOR_OSA_X', 'low_limit': -7500, 'high_limit': 7500},
    {'dcs_devname':'PIXELATOR_OSA_Y', 'low_limit': -7500, 'high_limit': 7500},
    {'dcs_devname':'PIXELATOR_ZONEPLATE_Z', 'low_limit': -7500, 'high_limit': 7500},
    {'dcs_devname':'PIXELATOR_COARSE_X', 'low_limit': -7500, 'high_limit': 7500},
    {'dcs_devname':'PIXELATOR_COARSE_Y', 'low_limit': -7500, 'high_limit': 7500},
    {'dcs_devname':'PIXELATOR_COARSE_Z', 'low_limit': -7500, 'high_limit': 7500},
    {'dcs_devname':'PIXELATOR_DETECTOR_X', 'low_limit': -7500, 'high_limit': 7500},
    {'dcs_devname':'PIXELATOR_DETECTOR_Y', 'low_limit': -7500, 'high_limit': 7500},
    {'dcs_devname':'PIXELATOR_DETECTOR_Z', 'low_limit': -7500, 'high_limit': 7500},
    {'dcs_devname':'PIXELATOR_SAMPLE_X', 'low_limit': -7500, 'high_limit': 7500},
    {'dcs_devname':'PIXELATOR_SAMPLE_Y', 'low_limit': -7500, 'high_limit': 7500},
    {'dcs_devname':'PIXELATOR_ENERGY', 'low_limit': -7500, 'high_limit': 7500},
    {'dcs_devname':'PIXELATOR_SLIT_X', 'low_limit': -7500, 'high_limit': 7500},
    {'dcs_devname':'PIXELATOR_SLIT_Y', 'low_limit': -7500, 'high_limit': 7500},
    {'dcs_devname':'PIXELATOR_M3_PITCH', 'low_limit': -7500, 'high_limit': 7500},
    {'dcs_devname':'PIXELATOR_EPU_GAP', 'low_limit': -7500, 'high_limit': 7500},
    {'dcs_devname':'PIXELATOR_EPU_OFFSET', 'low_limit': -7500, 'high_limit': 7500},
    {'dcs_devname':'PIXELATOR_EPU_HARMONIC', 'low_limit': -7500, 'high_limit': 7500},
    {'dcs_devname':'PIXELATOR_EPU_POLARIZATION', 'low_limit': -7500, 'high_limit': 7500},
    {'dcs_devname':'PIXELATOR_EPU_ANGLE', 'low_limit': -7500, 'high_limit': 7500}
]