

MAX_PIEZO_RANGE = 10.0
MAX_DELTA_FINE_RANGE_UM = MAX_PIEZO_RANGE / 2.0
MIN_INTERFER_RESET_RANGE_UM = MAX_DELTA_FINE_RANGE_UM / 4.0
MAX_DELTA_POS_CHNG_UM = 1000
MAX_FINE_SCAN_VELO = 10000
MAX_COARSE_SCAN_VELO = 2500
E712_MID_RANGE_VOLTS = 50
MAX_COARSE_MOTOR_VELO = 3500

MAX_DELTA_OFF_CENTER = 2 #um, if the current position is less than this value away from setpoint then skip moving coarse motor
