name: documentation

on:
  push:
    branches:
      - 3-host-manual-on-gh-pages
  pull_request:
    branches:
      - 3-host-manual-on-gh-pages
  workflow_dispatch:   # allow manual triggering
    inputs:
      deploy:
        description: 'Deploy wiki documentation'
        type: boolean
        required: true
        default: false

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Deploy Information
        if: ${{ github.event.inputs.deploy && env.python_version == env.python_deploy_version }}
        run: |
          echo "The HTML pyStxm documentation will be pushed to"
          echo " https://github.com/Canadian-Light-Source/pyStxm/tree/gh-pages"
          echo "The HTML pyStxm documentation will be deployed on"
          echo " https://Canadian-Light-Source.github.io/pyStxm/"

      - name: Install Requirements
        run: |
          python3 -m pip install --upgrade pip setuptools
          make install
          python3 -m pip list

      - name: Build Documentation
        run: |
          make html
          ls -lAFgh _build/html/index.html
          mkdir -p build
          mv _build/html/* build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/3-host-manual-on-gh-pages' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/
          force_orphan: true


